### PR TITLE
fix typo in fox-dog.txt

### PR DESCRIPTION
**Pull request by doublewinter0**

### CODE REVIEW

**Comment by blindpirate** [comment]
Sorry this repo is part of bytelegend.com, which is still in development. I'll leave this PR open and merge it once we finish. Sorry for the inconvenience.

**Comment by doublewinter0** [comment]
Friend from ShangHai, glad to see your reply, it's my pleasure!

**Comment by doublewinter0** [comment]
> Sorry this repo is part of bytelegend.com, which is still in development. I'll leave this PR open and merge it once we finish. Sorry for the inconvenience.



> _No description provided._



> Sorry this repo is part of bytelegend.com, which is still in development. I'll leave this PR open and merge it once we finish. Sorry for the inconvenience.

**Comment by doublewinter0** [comment]
> Sorry this repo is part of bytelegend.com, which is still in development. I'll leave this PR open and merge it once we finish. Sorry for the inconvenience.

Friend from ShangHai, glad to see your reply, it's my pleasure!

**Pull request closed without merging**
